import { Blob as NodeBlob } from 'node:buffer';
import { describe, expect, it } from 'vitest';
import { z } from 'zod';

import {
  BlobRecordSchema,
  BookSchema,
  CharacterRigSchema,
  CharacterSchema,
  DrawingSchema,
  ExportManifestSchema,
  MotionClipSchema,
  PageSchema,
  SettingsSchema,
} from './schemas';
import { BONE_IDS, JOINT_NAMES } from './skeleton';

const id = '00000000-0000-4000-8000-000000000010';
const id2 = '00000000-0000-4000-8000-000000000011';
const point = [0, 0] as [number, number];
const rig = {
  schemaVersion: 1 as const,
  joints: Object.fromEntries(JOINT_NAMES.map((name) => [name, point])),
  mesh: { vertices: [0, 0, 1, 1], triangles: [0, 1, 0] },
  weights: [[{ boneIndex: 0, w: 1 }], [{ boneIndex: 0, w: 1 }]],
  meshMethod: 'grid' as const,
  textureSize: [2, 2] as [number, number],
};
const motion = {
  schemaVersion: 1 as const,
  id: 'wave',
  name: { ja: '波', en: 'Wave' },
  keywords: { ja: ['ばいばい'], en: ['bye'] },
  category: 'greeting' as const,
  fps: 30 as const,
  frameCount: 2,
  loop: true,
  rootTranslation: [point, point],
  restAngles: Object.fromEntries(BONE_IDS.map((bone) => [bone, 0])),
  frames: Object.fromEntries(BONE_IDS.map((bone) => [bone, [0, 0]])),
};

const fixtures: Array<[string, z.ZodTypeAny, unknown, unknown[]]> = [
  [
    'BlobRecord',
    BlobRecordSchema,
    { id, mime: 'image/png', data: new NodeBlob(['x']), size: 1, createdAt: 1 },
    [
      { id, mime: 'image/png', data: 'x', size: 1, createdAt: 1 },
      { id, mime: '', data: new NodeBlob(['x']), size: 1, createdAt: 1 },
      {
        id,
        mime: 'image/png',
        data: new NodeBlob(['x']),
        size: -1,
        createdAt: 1,
      },
      {
        id,
        mime: 'image/png',
        data: new NodeBlob(['x']),
        size: 1,
        createdAt: Number.NaN,
      },
      {
        id,
        mime: 'image/png',
        data: new NodeBlob(['x']),
        size: 1,
        createdAt: 1,
        extra: true,
      },
    ],
  ],
  [
    'Drawing',
    DrawingSchema,
    { id, createdAt: 1, source: 'file', imageBlobId: id2, width: 2, height: 2 },
    [
      {
        id,
        createdAt: 1,
        source: 'url',
        imageBlobId: id2,
        width: 2,
        height: 2,
      },
      {
        id,
        createdAt: 1,
        source: 'file',
        imageBlobId: id2,
        width: 0,
        height: 2,
      },
      {
        id,
        createdAt: 1,
        source: 'file',
        imageBlobId: id2,
        width: 2,
        height: 2,
        extra: true,
      },
      {
        id,
        createdAt: 1,
        source: 'file',
        imageBlobId: 'bad',
        width: 2,
        height: 2,
      },
      { id, source: 'file', imageBlobId: id2, width: 2, height: 2 },
    ],
  ],
  [
    'CharacterRig',
    CharacterRigSchema,
    rig,
    [
      { ...rig, schemaVersion: 2 },
      { ...rig, meshMethod: 'bad' },
      { ...rig, joints: { ...rig.joints, extra: point } },
      { ...rig, mesh: { ...rig.mesh, triangles: [0, 1, 0.5] } },
      { ...rig, mesh: { ...rig.mesh, triangles: [0, 1, 9] } },
    ],
  ],
  [
    'Character',
    CharacterSchema,
    {
      id,
      name: 'Momo',
      createdAt: 1,
      updatedAt: 1,
      rigType: 'humanoid',
      drawingId: id2,
      textureBlobId: id2,
      thumbBlobId: id2,
      rig: null,
      effectPrefs: {},
    },
    [
      {
        id,
        name: 'x'.repeat(51),
        createdAt: 1,
        updatedAt: 1,
        rigType: 'humanoid',
        drawingId: id2,
        textureBlobId: id2,
        thumbBlobId: id2,
        rig: null,
        effectPrefs: {},
      },
      {
        id,
        name: 'Momo',
        createdAt: 1,
        updatedAt: 1,
        rigType: 'other',
        drawingId: id2,
        textureBlobId: id2,
        thumbBlobId: id2,
        rig: null,
        effectPrefs: {},
      },
      {
        id,
        name: 'Momo',
        createdAt: Number.NaN,
        updatedAt: 1,
        rigType: 'humanoid',
        drawingId: id2,
        textureBlobId: id2,
        thumbBlobId: id2,
        rig: null,
        effectPrefs: {},
      },
      {
        id,
        name: 'Momo',
        createdAt: 1,
        updatedAt: 1,
        rigType: 'humanoid',
        drawingId: 'bad',
        textureBlobId: id2,
        thumbBlobId: id2,
        rig: null,
        effectPrefs: {},
      },
      {
        id,
        name: 'Momo',
        createdAt: 1,
        updatedAt: 1,
        rigType: 'humanoid',
        drawingId: id2,
        textureBlobId: id2,
        thumbBlobId: id2,
        rig: null,
        effectPrefs: {},
        extra: true,
      },
    ],
  ],
  [
    'Book',
    BookSchema,
    { id, title: 'Story', createdAt: 1, updatedAt: 1, pageOrder: [id2] },
    [
      { id, title: 'x'.repeat(101), createdAt: 1, updatedAt: 1, pageOrder: [] },
      { id, title: 'Story', createdAt: 1, updatedAt: 1, pageOrder: ['bad'] },
      {
        id,
        title: 'Story',
        createdAt: Number.NaN,
        updatedAt: 1,
        pageOrder: [],
      },
      {
        id,
        title: 'Story',
        createdAt: 1,
        updatedAt: 1,
        pageOrder: [],
        extra: true,
      },
      { id, title: 'Story', createdAt: 1, updatedAt: 1 },
    ],
  ],
  [
    'Page',
    PageSchema,
    {
      id,
      bookId: id2,
      backgroundId: 'plain_cream',
      text: '',
      effectIds: [],
      advance: 'tap',
      createdAt: 1,
      updatedAt: 1,
    },
    [
      {
        id,
        bookId: id2,
        backgroundId: 'plain_cream',
        text: 'x'.repeat(501),
        effectIds: [],
        advance: 'tap',
        createdAt: 1,
        updatedAt: 1,
      },
      {
        id,
        bookId: id2,
        backgroundId: 'plain_cream',
        text: '',
        effectIds: ['a', 'b', 'c', 'd'],
        advance: 'tap',
        createdAt: 1,
        updatedAt: 1,
      },
      {
        id,
        bookId: id2,
        backgroundId: 'plain_cream',
        text: '',
        effectIds: [],
        advance: 'later',
        createdAt: 1,
        updatedAt: 1,
      },
      {
        id,
        bookId: id2,
        backgroundId: 'plain_cream',
        text: '',
        effectIds: [],
        advance: 'tap',
        createdAt: Number.NaN,
        updatedAt: 1,
      },
      {
        id,
        bookId: id2,
        backgroundId: 'plain_cream',
        text: '',
        effectIds: [],
        advance: 'tap',
        createdAt: 1,
        updatedAt: 1,
        extra: true,
      },
    ],
  ],
  [
    'Settings',
    SettingsSchema,
    { key: 'locale', value: 'ja' },
    [
      { key: '', value: 'ja' },
      { key: 'x'.repeat(101), value: 'ja' },
      {},
      { key: 'locale', value: 'ja', extra: true },
      { key: 1, value: 'ja' },
    ],
  ],
  [
    'MotionClip',
    MotionClipSchema,
    motion,
    [
      { ...motion, id: 'Bad-ID' },
      { ...motion, category: 'other' },
      { ...motion, fps: 25 },
      { ...motion, frameCount: 1 },
      { ...motion, frames: { ...motion.frames, torso: [0] } },
    ],
  ],
  [
    'ExportManifest',
    ExportManifestSchema,
    {
      formatVersion: 1,
      appVersion: '0.1.0',
      exportedAt: 1,
      characterIds: [id],
      bookIds: [],
    },
    [
      {
        formatVersion: 2,
        appVersion: '0.1.0',
        exportedAt: 1,
        characterIds: [],
        bookIds: [],
      },
      {
        formatVersion: 1,
        appVersion: '',
        exportedAt: 1,
        characterIds: [],
        bookIds: [],
      },
      {
        formatVersion: 1,
        appVersion: '0.1.0',
        exportedAt: Number.NaN,
        characterIds: [],
        bookIds: [],
      },
      {
        formatVersion: 1,
        appVersion: '0.1.0',
        exportedAt: 1,
        characterIds: ['bad'],
        bookIds: [],
      },
      {
        formatVersion: 1,
        appVersion: '0.1.0',
        exportedAt: 1,
        characterIds: [],
        bookIds: [],
        extra: true,
      },
    ],
  ],
];

describe('schema rejection matrix', () => {
  it.each(fixtures)(
    '%s rejects five invalid boundary values',
    (_name, schema, valid, invalid) => {
      expect(schema.parse(valid)).toBeDefined();
      for (const value of invalid)
        expect(schema.safeParse(value).success).toBe(false);
    },
  );
});
